version: 2
jobs:
  build:
    working_directory: /tmp/petstore
    docker:
      - image: microsoft/aspnetcore-build
    steps:
      - checkout
      - run:
          name: CD to src
          command: |
            cd src
            ls
            dotnet restore
            dotnet build --no-restore --configuration Release
      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory
          root: .
          # Must be relative path from root
          paths:
            - src/PetStore.Images/bin
            - Dockerfile   
  publish:
    working_directory: /tmp/petstore
    docker:
      - image: microsoft/aspnetcore-build
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: ./
      - run: |
          ls
      - run: |
          docker login -u $dockeruser -p $dockerpassword
          docker build -t demopetstore/images:latest -t demopetstore/images:0.$CIRCLE_BUILD_NUM .
          docker push demopetstore/images
         
workflows:
  version: 2
  build_and_publish:
    jobs:
      - build
      - publish:
          context: docker
          requires:
            - build